// Sample content for the tap2news app UI kit. Telugu-first hyperlocal feed (geo-fenced to AP/Telangana).
window.DN_DATA = {
  language: { code: 'te', native: 'తెలుగు', location: 'Vijayawada, AP' },
  breaking: [
    'కేబినెట్‌లో కొత్త ఐటీ పాలసీకి ఆమోదం — 2 లక్షల ఉద్యోగాల లక్ష్యం',
    'తీర జిల్లాలకు భారీ వర్ష హెచ్చరిక; మత్స్యకారులకు అలర్ట్',
    'సెన్సెక్స్ 400 పాయింట్లు లాభంతో ముగింపు',
  ],
  rail: [
    { kind: 'gold', label: 'Gold 22K', value: '₹71,240', sub: 'per 10g · Hyd', delta: 180 },
    { kind: 'market', label: 'Nifty 50', value: '24,318', delta: -96 },
    { kind: 'weather', label: 'Vijayawada', value: '34°', sub: 'AQI 82 · Haze' },
    { kind: 'cricket', label: 'IND vs AUS', value: '286/4', sub: '48.2 ov' },
  ],
  sections: [
    { category: 'mynews', label: 'మీ వార్తలు' },
    { category: 'politics', label: 'రాజకీయాలు' },
    { category: 'cinema', label: 'సినిమా' },
    { category: 'shorts', label: 'వైరల్ షార్ట్స్' },
    { category: 'sports', label: 'క్రికెట్' },
    { category: 'jobs', label: 'ఉద్యోగాలు' },
    { category: 'finance', label: 'ఫైనాన్స్' },
    { category: 'astrology', label: 'జాతకం' },
    { category: 'health', label: 'ఆరోగ్యం' },
    { category: 'business', label: 'బిజినెస్' },
    { category: 'cooking', label: 'వంటలు' },
  ],
  featured: [
    { region: 'Telangana', category: 'crime', headline: 'Gooty: సైబర్ క్రైమ్స్, పోక్సో చట్టాలపై స్టూడెంట్స్‌కు పోలీస్ క్లాస్!', time: '11:37 PM', read: '1 min read' },
    { region: 'Andhra Pradesh', category: 'politics', headline: 'పోలవరం ప్రాజెక్టును సందర్శించిన సీఎం చంద్రబాబు', time: '9:50 PM', read: '2 min read' },
    { region: 'National', category: 'breaking', headline: 'కేబినెట్‌లో కొత్త ఐటీ పాలసీకి ఆమోదం — 2 లక్షల ఉద్యోగాల లక్ష్యం', time: '8:20 PM', read: '3 min read' },
    { region: 'Hyderabad', category: 'business', headline: 'హైదరాబాద్‌లో కొత్త ఐటీ పార్క్‌కు శంకుస్థాపన', time: '7:05 PM', read: '2 min read' },
    { region: 'Tollywood', category: 'cinema', headline: 'సంక్రాంతికి భారీ పోటీ — మూడు పెద్ద సినిమాలు రిలీజ్', time: '6:40 PM', read: '1 min read' },
    { region: 'Sports', category: 'sports', headline: 'హోం టెస్ట్ సిరీస్‌కు భారత జట్టు ప్రకటన; కొత్త ఆటగాడికి చోటు', time: '5:15 PM', read: '2 min read' },
    { region: 'Andhra Pradesh', category: 'jobs', headline: 'APPSC గ్రూప్-II నోటిఫికేషన్ విడుదల — 1,200 ఖాళీలు', time: '4:00 PM', read: '1 min read' },
    { region: 'Weather', category: 'weather', headline: 'తీర జిల్లాలకు భారీ వర్ష హెచ్చరిక; వారాంతంలో గాలివానలు', time: '2:30 PM', read: '2 min read' },
  ],
  stories: [
    { id: 1, category: 'breaking', breaking: true, layout: 'hero', headline: 'తీర జిల్లాలకు భారీ వర్ష హెచ్చరిక; వారాంతంలో గాలివానలు',
      summary: 'IMD ప్రకారం రాబోయే 48 గంటల్లో బలమైన గాలులు, స్థానిక వరదల ముప్పు. మత్స్యకారులు సముద్రంలోకి వెళ్లవద్దని సూచన.',
      source: 'TV9', location: 'Vijayawada', time: '8 min', verified: true, body: [
        'భారత వాతావరణ శాఖ (IMD) ఆంధ్రప్రదేశ్ తీర జిల్లాలకు వారాంతం వరకు భారీ వర్ష హెచ్చరిక జారీ చేసింది.',
        'బంగాళాఖాతంలో ఏర్పడిన అల్పపీడనం కారణంగా గాలివానలు, స్థానిక వరదల ముప్పు ఉందని అధికారులు తెలిపారు.',
        'మత్స్యకారులు సముద్రంలోకి వెళ్లవద్దని, ప్రజలు అప్రమత్తంగా ఉండాలని ప్రభుత్వం విజ్ఞప్తి చేసింది.',
      ] },
    { id: 2, category: 'cinema', layout: 'row', headline: 'టాలీవుడ్ హీరో తదుపరి చిత్రం సంక్రాంతికి — ఫస్ట్ లుక్ విడుదల',
      summary: 'ఫెస్టివల్ సీజన్‌లో భారీ పోటీకి రంగం సిద్ధం; హైదరాబాద్‌లో చివరి షెడ్యూల్ పూర్తి.',
      source: 'Sakshi', location: 'Hyderabad', time: '1 hr', aiRewritten: true, body: [
        'ప్రముఖ టాలీవుడ్ హీరో నటిస్తున్న చిత్రం వచ్చే సంక్రాంతికి విడుదల కానుందని నిర్మాతలు ప్రకటించారు.',
        'చిత్రం చివరి షెడ్యూల్ హైదరాబాద్‌లో పూర్తయిందని, పోస్ట్ ప్రొడక్షన్ పనులు వేగంగా జరుగుతున్నాయని తెలిపారు.',
      ] },
    { id: 3, category: 'jobs', layout: 'row', headline: 'APPSC గ్రూప్-II నోటిఫికేషన్ విడుదల — 1,200 ఖాళీలు',
      summary: 'ఆన్‌లైన్ దరఖాస్తులు ఈ నెలాఖరు వరకు; పరీక్ష మార్చిలో నిర్వహణ.',
      source: 'tap2news', location: 'AP', time: '2 hr', verified: true, body: [
        'ఆంధ్రప్రదేశ్ పబ్లిక్ సర్వీస్ కమిషన్ (APPSC) గ్రూప్-II పోస్టులకు 1,200 ఖాళీలతో నోటిఫికేషన్ విడుదల చేసింది.',
        'అర్హులైన అభ్యర్థులు ఈ నెలాఖరులోగా ఆన్‌లైన్‌లో దరఖాస్తు చేసుకోవాలని కమిషన్ సూచించింది.',
      ] },
    { id: 4, category: 'politics', layout: 'row', headline: 'రాష్ట్ర కేబినెట్‌లో కొత్త ఐటీ పాలసీకి ఆమోదం',
      summary: 'రానున్న ఐదేళ్లలో 2 లక్షల ఉద్యోగాల కల్పనే లక్ష్యంగా విధానం.',
      source: 'Eenadu', location: 'Amaravati', time: '3 hr', verified: true, body: [
        'రాష్ట్ర మంత్రివర్గం సమావేశంలో కొత్త ఐటీ పాలసీకి ఆమోదం లభించింది.',
      ] },
    { id: 5, category: 'sports', layout: 'compact', headline: 'హోం టెస్ట్ సిరీస్‌కు భారత జట్టు ప్రకటన',
      source: 'Cricbuzz', time: '4 hr', verified: true, body: ['రాబోయే హోం టెస్ట్ సిరీస్‌కు భారత జట్టును బీసీసీఐ ప్రకటించింది.'] },
    { id: 6, category: 'crime', layout: 'compact', headline: 'నగరంలో సైబర్ మోసం ముఠా అరెస్ట్; రూ.2 కోట్లు స్వాధీనం',
      source: 'ABN', location: 'Guntur', time: '5 hr', body: ['పోలీసులు సైబర్ మోసాలకు పాల్పడుతున్న ముఠాను అరెస్ట్ చేశారు.'] },
  ],
  explore: [
    { category: 'politics', label: 'Politics' }, { category: 'crime', label: 'Crime' },
    { category: 'cinema', label: 'Cinema' }, { category: 'sports', label: 'Sports' },
    { category: 'jobs', label: 'Jobs' }, { category: 'business', label: 'Business' },
    { category: 'education', label: 'Education' }, { category: 'health', label: 'Health' },
    { category: 'weather', label: 'Weather' }, { category: 'astrology', label: 'Astrology' },
    { category: 'gold', label: 'Gold' }, { category: 'tech', label: 'Tech' },
  ],
  panchang: { tithi: 'Dashami', nakshatra: 'Uttara', rahu: '1:30–3:00 PM', lucky: '7 · Red' },
  poll: {
    q: 'కొత్త ఐటీ పాలసీతో మీ జిల్లాకు ఉద్యోగాలు వస్తాయా?',
    options: [ { t: 'ఖచ్చితంగా వస్తాయి', v: 46 }, { t: 'చూడాలి', v: 38 }, { t: 'రావు', v: 16 } ],
    votes: '12.4K',
  },
  quiz: {
    tag: 'ఆరోగ్యం',
    q: 'రోజుకు ఎంత నీరు తాగాలి?',
    options: ['1 లీటర్', '2–3 లీటర్లు', '5 లీటర్లు'],
    answer: 1,
    fact: 'వైద్యుల ప్రకారం పెద్దలు రోజుకు 2–3 లీటర్ల నీరు తాగాలి — వేసవిలో ఇంకా ఎక్కువ.',
  },
  viral: {
    headline: 'వైరల్: గోదావరి వరదలో యువకుడి సాహసం — 3 గంటల్లో 2M వ్యూస్',
    views: '2.1M', shares: '48K', time: '3 hr',
  },
  suggest: ['cinema', 'jobs', 'astrology', 'health', 'sports'],
  engage: {
    politics: { type: 'poll', poll: { q: 'కొత్త ఐటీ పాలసీతో మీ జిల్లాకు ఉద్యోగాలు వస్తాయా?', options: [ { t: 'ఖచ్చితంగా వస్తాయి', v: 46 }, { t: 'చూడాలి', v: 38 }, { t: 'రావు', v: 16 } ], votes: '12.4K' } },
    sports: { type: 'poll', poll: { q: 'హోం టెస్ట్ సిరీస్ ఎవరు గెలుస్తారు?', options: [ { t: 'ఇండియా', v: 78 }, { t: 'ఆస్ట్రేలియా', v: 14 }, { t: 'డ్రా', v: 8 } ], votes: '31.2K' } },
    jobs: { type: 'poll', poll: { q: 'మీరు ఏ ఉద్యోగాలకు ప్రాధాన్యం ఇస్తారు?', options: [ { t: 'ప్రభుత్వ', v: 64 }, { t: 'ప్రైవేట్', v: 22 }, { t: 'సొంత వ్యాపారం', v: 14 } ], votes: '8.9K' } },
    cinema: { type: 'quiz', quiz: { tag: 'సినిమా', q: 'తొలి తెలుగు టాకీ చిత్రం ఏది?', options: ['భక్త ప్రహ్లాద', 'మాయాబజార్', 'పాతాళ భైరవి'], answer: 0, fact: '1932లో విడుదలైన "భక్త ప్రహ్లాద" తొలి తెలుగు టాకీ చిత్రం.' } },
    health: { type: 'quiz', quiz: { tag: 'ఆరోగ్యం', q: 'రోజుకు ఎంత నీరు తాగాలి?', options: ['1 లీటర్', '2–3 లీటర్లు', '5 లీటర్లు'], answer: 1, fact: 'వైద్యుల ప్రకారం పెద్దలు రోజుకు 2–3 లీటర్ల నీరు తాగాలి — వేసవిలో ఇంకా ఎక్కువ.' } },
    crime: { type: 'poll', poll: { q: 'మీ ప్రాంతంలో రాత్రి భద్రత ఎలా ఉంది?', options: [ { t: 'బాగుంది', v: 41 }, { t: 'పర్వాలేదు', v: 35 }, { t: 'బాగోలేదు', v: 24 } ], votes: '5.6K' } },
  },
  local: [
    { id: 'l1', category: 'crime', headline: 'బెంజ్ సర్కిల్ వద్ద ట్రాఫిక్ మళ్లింపు — ఫ్లైఓవర్ పనులు', source: 'City desk', time: '25 min' },
    { id: 'l2', category: 'weather', headline: 'నగరంలో సాయంత్రం భారీ వర్షం అవకాశం; AQI 82', source: 'IMD', time: '40 min', verified: true },
    { id: 'l3', category: 'jobs', headline: 'ఆటోనగర్‌లో ఉద్యోగ మేళా — 600 పోస్టులు, రేపు ఉదయం 10కి', source: 'tap2news', time: '1 hr' },
  ],
};
