// tap2news Admin v2 — command center seed data.
window.AD2 = {
  user: { name: 'Priya Rao', role: 'Managing Editor', initials: 'PR' },
  hubs: [
    { id: 'command', icon: 'gauge', label: 'Command' },
    { id: 'newsroom', icon: 'pen-line', label: 'Newsroom', badge: 8 },
    { id: 'infra', icon: 'server', label: 'Infra & AI' },
    { id: 'sources', icon: 'rss', label: 'Sources & APIs' },
    { id: 'growth', icon: 'trending-up', label: 'Growth' },
  ],
  queue: [
    { id: 1, headline: 'తీర జిల్లాలకు భారీ వర్ష హెచ్చరిక; వారాంతంలో గాలివానలు', category: 'breaking', lang: 'te', source: 'TV9', conf: 96 },
    { id: 2, headline: 'Cabinet clears new IT policy; targets 200,000 jobs', category: 'politics', lang: 'en', source: 'PTI', conf: 91 },
    { id: 3, headline: 'டாலிவுட் நடிகரின் அடுத்த படம் பொங்கலுக்கு', category: 'cinema', lang: 'ta', source: 'Dinamalar', conf: 88 },
    { id: 4, headline: 'APPSC Group-II: 1,200 vacancies, apply by month end', category: 'jobs', lang: 'en', source: 'Desk', conf: 99 },
    { id: 5, headline: 'ನಗರದಲ್ಲಿ ಸೈಬರ್ ವಂಚನೆ ಜಾಲ ಬಂಧನ; ₹2 ಕೋಟಿ ವಶ', category: 'crime', lang: 'kn', source: 'Prajavani', conf: 74 },
  ],
  draft: {
    headline: 'తీర జిల్లాలకు భారీ వర్ష హెచ్చరిక; వారాంతంలో గాలివానలు',
    short: 'తీర జిల్లాలకు వర్ష హెచ్చరిక',
    summary: 'IMD ప్రకారం రాబోయే 48 గంటల్లో బలమైన గాలులు, స్థానిక వరదల ముప్పు. మత్స్యకారులు సముద్రంలోకి వెళ్లవద్దని సూచన.',
    seoTitle: 'AP coastal districts rain alert — IMD warning | tap2news',
    slug: 'ap-coastal-rain-alert-weekend-imd',
    meta: 'IMD issues heavy rain alert for Andhra Pradesh coastal districts. Squally winds, local flooding likely.',
    tags: ['Weather', 'IMD', 'Andhra Pradesh', 'Rain alert'],
    push: 'Heavy rain alert for coastal AP this weekend — stay safe. Updates on tap2news.',
    source: 'TV9', category: 'breaking', lang: 'Telugu', conf: 96,
  },
  models: [
    { name: 'Gemini 2.0 Flash', role: 'Rewrite + classify', share: 62, cost: '₹0.09/story', p95: 1.9, ok: true },
    { name: 'Claude Sonnet', role: 'Fact-check · long-form', share: 22, cost: '₹0.31/story', p95: 3.2, ok: true },
    { name: 'GPT-4o mini', role: 'Headlines · push copy', share: 11, cost: '₹0.05/story', p95: 1.1, ok: true },
    { name: 'DeepSeek V3', role: 'Fallback · batch archive', share: 5, cost: '₹0.02/story', p95: 4.8, ok: false },
  ],
  mcps: [
    { name: 'Context7', use: 'Live docs — Next.js, Supabase, Tailwind', stars: 5, on: true },
    { name: 'Filesystem', use: 'Read/write project code', stars: 5, on: true },
    { name: 'GitHub', use: 'Commits, PRs, issues on tap2news repo', stars: 5, on: true },
    { name: 'Playwright', use: 'E2E: login, search, UI screenshots', stars: 5, on: true },
    { name: 'Supabase', use: 'Tables, SQL, RLS, storage, auth', stars: 5, on: true },
    { name: 'Fetch', use: 'Read article URLs → markdown', stars: 4, on: true },
    { name: 'PostgreSQL', use: 'Query tuning, indexes, debugging', stars: 4, on: true },
    { name: 'Brave Search', use: 'Breaking verification, fact sources', stars: 4, on: false },
  ],
  redisKeys: [
    { key: 'feed:te:hyd:mynews', ttl: '42s', hits: '18.2K/m', size: '214KB' },
    { key: 'feed:hi:lko:politics', ttl: '31s', hits: '9.8K/m', size: '186KB' },
    { key: 'gold:rates:in', ttl: '9m', hits: '6.1K/m', size: '2KB' },
    { key: 'cricket:live:ind-aus', ttl: '8s', hits: '22.4K/m', size: '11KB' },
    { key: 'trends:ta:chennai', ttl: '4m', hits: '3.2K/m', size: '96KB' },
  ],
  queues: [
    { name: 'ingest-rss', waiting: 34, active: 6, failed: 2, done: '48.2K' },
    { name: 'ai-rewrite', waiting: 12, active: 8, failed: 1, done: '31.7K' },
    { name: 'push-fanout', waiting: 0, active: 2, failed: 0, done: '1.4M' },
    { name: 'thumb-gen', waiting: 7, active: 3, failed: 4, done: '29.9K' },
    { name: 'social-syndicate', waiting: 3, active: 1, failed: 0, done: '12.3K' },
  ],
  pg: [
    { k: 'Replication lag', v: '0.4s', ok: true }, { k: 'Connections', v: '212 / 500', ok: true },
    { k: 'Cache hit ratio', v: '99.1%', ok: true }, { k: 'Slowest query', v: 'get_feed 84ms', ok: true },
    { k: 'Table bloat (articles)', v: '6%', ok: true }, { k: 'WAL size', v: '1.2GB', ok: false },
  ],
  cdn: [
    { zone: 'feed-api (in-south)', hit: 94, reqs: '212K/m' },
    { zone: 'images (r2)', hit: 98, reqs: '480K/m' },
    { zone: 'article pages', hit: 88, reqs: '96K/m' },
  ],
  revenue: [
    { src: 'AdSense / Ad Manager', v: 46, amt: '₹4.61L' }, { src: 'Sponsored stories', v: 22, amt: '₹2.20L' },
    { src: 'tap2news Plus', v: 17, amt: '₹1.71L' }, { src: 'E-paper', v: 9, amt: '₹0.90L' },
    { src: 'Local ads', v: 6, amt: '₹0.61L' },
  ],
  topStories: [
    { t: 'వర్ష హెచ్చరిక — తీర జిల్లాలు', v: '412K', cat: 'breaking' },
    { t: 'IT policy: 2L jobs', v: '284K', cat: 'politics' },
    { t: 'సంక్రాంతి సినిమా వార్', v: '221K', cat: 'cinema' },
    { t: 'APPSC 1,200 posts', v: '198K', cat: 'jobs' },
  ],
  langSplit: [
    { l: 'తెలుగు', pct: 38, c: 'var(--cat-politics)' }, { l: 'हिन्दी', pct: 27, c: 'var(--brand)' },
    { l: 'தமிழ்', pct: 16, c: 'var(--cat-sports)' }, { l: 'ಕನ್ನಡ', pct: 11, c: 'var(--cat-cinema)' },
    { l: 'Other', pct: 8, c: 'var(--cat-jobs)' },
  ],
};
